### ISSUE TITLE
请问 `font_load` 在哪里

### ISSUE THREAD

**Issue by Wind-stormger** [kaixindelele/ssd1306-MicroPython-ESP32-Chinese#2]
有以下报错
`AttributeError: 'SSD1306_I2C' object has no attribute 'font_load'`
我检查了很久在ssd1306.py中没有 `font_load`
期待回复

**Comment by kaixindelele** [comment]
需要刷特定的固件，那个py文件里面没有定义。这个库很久都没用了，我也不想维护了，你最好加我readme里面提到的那个群，这个问题关了。

**Comment by ceca00** [comment]
好嘞哥
