### ISSUE TITLE
ssd1306.py的重要性

### ISSUE THREAD

**Issue by ukinglli** [kaixindelele/ssd1306-MicroPython-ESP32-Chinese#4]
ssd1306.py在作者的readme里面有，这个很重要，一定要替换掉默认的ssd1306.py 我也没仔细看，粗心的以为跟原来的驱动一样，导致一直报错：
AttributeError: 'SSD1306_I2C' object has no attribute 'font_load'

假装严谨的还到处找font_load的定义在哪。

后来者要注意一下，作者也可以readme标注一下，这个的重要性

**Comment by yonggithub** [comment]
@ukinglli @kaixindelele 为什么替换调ssd1306.py文件还是报错.文件里面也没有font_load方法呀?
![image](https://user-images.githubusercontent.com/25076827/156301641-29336c4f-4187-4084-8565-255fa7739b31.png)

===============解决方法=================
![image](https://user-images.githubusercontent.com/25076827/156302278-fd6ac014-3847-45e4-81a6-0ba633ac9589.png)

坏消息是: 我的设备是PICO -.-

**Comment by kaixindelele** [comment]
pico不能刷固件吗？不刷固件是没有load_font函数的~

**Comment by sushipan** [comment]
大神,pico的固件有没有呢 @kaixindelele
